import io
from datetime import datetime
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm, cm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak, Image
)
from reportlab.lib.enums import TA_CENTER, TA_RIGHT, TA_LEFT


def generate_dashboard_pdf(summary: dict, monthly: list | None = None) -> io.BytesIO:
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, topMargin=2*cm, bottomMargin=2*cm)
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle("Title2", parent=styles["Title"], fontSize=18, spaceAfter=6)
    subtitle_style = ParagraphStyle("Sub", parent=styles["Normal"], fontSize=10, textColor=colors.grey, spaceAfter=12)
    cell_style = ParagraphStyle("Cell", parent=styles["Normal"], fontSize=9, leading=12)

    elements = []
    elements.append(Paragraph("Incentive House ERP", title_style))
    elements.append(Paragraph(f"Dashboard Report — Generated {datetime.now().strftime('%Y-%m-%d %H:%M')}", subtitle_style))
    elements.append(Spacer(1, 4*mm))

    kpi_data = [
        ["Metric", "Value"],
        ["Total PNRs", str(summary.get("total_pnrs", 0))],
        ["Active PNRs", str(summary.get("active_pnrs", 0))],
        ["Total Sales", f"EGP {summary.get('total_sales', 0):,.2f}"],
        ["Total Purchases", f"EGP {summary.get('total_purchases', 0):,.2f}"],
        ["Bank Balance", f"EGP {summary.get('bank_balance', 0):,.2f}"],
        ["Outstanding Receivables", f"EGP {summary.get('outstanding_receivables', 0):,.2f}"],
        ["Total Clients", str(summary.get("total_clients", 0))],
        ["Total Vendors", str(summary.get("total_vendors", 0))],
    ]
    kpi_table = Table(kpi_data, colWidths=[180, 200])
    kpi_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1a237e")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTSIZE", (0, 0), (-1, 0), 10),
        ("FONTSIZE", (0, 1), (-1, -1), 9),
        ("ALIGN", (0, 0), (-1, -1), "LEFT"),
        ("ALIGN", (1, 1), (1, -1), "RIGHT"),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f5f5f5")]),
    ]))
    elements.append(kpi_table)
    elements.append(Spacer(1, 6*mm))

    if monthly:
        elements.append(Paragraph("Monthly Breakdown", styles["Heading2"]))
        elements.append(Spacer(1, 3*mm))
        header = ["Month", "Revenue", "Expenses", "Net"]
        rows = [header]
        for m in monthly:
            rows.append([
                m.get("month", ""),
                f"EGP {m.get('revenue', 0):,.2f}",
                f"EGP {m.get('expenses', 0):,.2f}",
                f"EGP {m.get('net', 0):,.2f}",
            ])
        monthly_table = Table(rows, colWidths=[80, 100, 100, 100])
        monthly_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#283593")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTSIZE", (0, 0), (-1, -1), 8),
            ("ALIGN", (1, 0), (-1, -1), "RIGHT"),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f5f5f5")]),
        ]))
        elements.append(monthly_table)

    elements.append(Spacer(1, 10*mm))
    elements.append(Paragraph(f"Page 1 / Generated by IHE-ERP v2.4", ParagraphStyle("Footer", parent=styles["Normal"], fontSize=7, textColor=colors.grey, alignment=TA_CENTER)))

    doc.build(elements)
    buf.seek(0)
    return buf


def generate_list_pdf(title: str, headers: list[str], rows: list[list[str]]) -> io.BytesIO:
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, topMargin=2*cm, bottomMargin=2*cm)
    styles = getSampleStyleSheet()
    elements = []
    elements.append(Paragraph(title, ParagraphStyle("Title2", parent=styles["Title"], fontSize=16, spaceAfter=6)))
    elements.append(Paragraph(f"Generated {datetime.now().strftime('%Y-%m-%d %H:%M')}", ParagraphStyle("Sub", parent=styles["Normal"], fontSize=9, textColor=colors.grey, spaceAfter=12)))
    elements.append(Spacer(1, 4*mm))

    data = [headers] + rows
    col_count = len(headers)
    col_width = min(160, int(460 / max(col_count, 1)))
    table = Table(data, colWidths=[col_width] * col_count, repeatRows=1)
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1a237e")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTSIZE", (0, 0), (-1, -1), 7),
        ("ALIGN", (0, 0), (-1, -1), "LEFT"),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f5f5f5")]),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ]))
    elements.append(table)
    elements.append(Spacer(1, 8*mm))
    elements.append(Paragraph(f"Page 1 / {len(rows)} records", ParagraphStyle("Footer", parent=styles["Normal"], fontSize=7, textColor=colors.grey, alignment=TA_CENTER)))
    doc.build(elements)
    buf.seek(0)
    return buf
